name: Release

on:
    push:
        tags:
            - "v[0-9]+.*"

permissions:
    contents: write # Needed for creating releases and uploading assets

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1
    # Default binary name
    BINARY_NAME: awsomarchy

jobs:
    create-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/create-gh-release-action@v1
              with:
                  # If you have a changelog file, specify it here
                  # changelog: CHANGELOG.md
                  token: ${{ secrets.GITHUB_TOKEN }}

    upload-assets:
        needs: create-release
        strategy:
            fail-fast: false
            matrix:
                include:
                    - target: x86_64-unknown-linux-gnu
                      os: ubuntu-latest
                    - target: x86_64-unknown-linux-musl
                      os: ubuntu-latest
                    - target: x86_64-apple-darwin
                      os: macos-latest
                    - target: x86_64-pc-windows-msvc
                      os: windows-latest
                    - target: aarch64-unknown-linux-gnu
                      os: ubuntu-latest
                    - target: aarch64-unknown-linux-musl
                      os: ubuntu-latest
                    - target: aarch64-apple-darwin
                      os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Install cross-compilation dependencies
              if: matrix.target == 'x86_64-unknown-linux-musl' || contains(matrix.target, 'musl')
              run: |
                  sudo apt-get update
                  sudo apt-get install -y musl-tools musl-dev

            - name: Install cross-compilation dependencies for aarch64
              if: contains(matrix.target, 'aarch64') && matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gcc-aarch64-linux-gnu

            - name: Set cross-compilation environment
              if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
              run: |
                  echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
                  echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

            - uses: taiki-e/upload-rust-binary-action@v1
              with:
                  bin: ${{ env.BINARY_NAME }}
                  target: ${{ matrix.target }}
                  include: LICENSE,README.md
                  checksum: sha256
                  token: ${{ secrets.GITHUB_TOKEN }}

    test-installation:
        needs: upload-assets
        continue-on-error: true
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
        runs-on: ${{ matrix.os }}
        steps:
            - name: Test installation on Linux/macOS
              if: matrix.os != 'windows-latest'
              shell: bash
              run: |
                  # Get the latest version tag
                  VERSION=$GITHUB_REF_NAME
                  # Use curl to download and test the binary
                  curl -L https://github.com/${{ github.repository }}/releases/download/${VERSION}/${{ env.BINARY_NAME }}-${{ matrix.target }}.tar.gz -o ${{ env.BINARY_NAME }}.tar.gz
                  tar xzf ${{ env.BINARY_NAME }}.tar.gz
                  ./${{ env.BINARY_NAME }} help

            - name: Test installation on Windows
              if: matrix.os == 'windows-latest'
              shell: pwsh
              run: |
                  # Get the latest version tag
                  $VERSION = $env:GITHUB_REF_NAME
                  # Use PowerShell to download and test the binary
                  Invoke-WebRequest -Uri "https://github.com/${{ github.repository }}/releases/download/${VERSION}/${{ env.BINARY_NAME }}-${{ matrix.target }}.zip" -OutFile "${{ env.BINARY_NAME }}.zip"
                  Expand-Archive -Path "${{ env.BINARY_NAME }}.zip" -DestinationPath "."
                  .\${{ env.BINARY_NAME }}.exe help